### ISSUE TITLE
Blockparser removes inclomplete blocks without notice

### ISSUE THREAD

**Issue by mattywausb** [jlolling/talendcomp_tSQLScriptParser#2]
The following script part will be ignored  without any information about incompletness or error

> BEGIN
>   SELECT mycol from myTable;
> END;

Pls add an output to the error log, that there is an open block in the script, that will not be transmitted.

**Comment by jlolling** [comment]
The problem here is, the parser is not really a SQL parser. The parser detects the start and end of statements by different rules.
In your block you could have more than one level of blocks and now the parser would have to understand exactly the structure.
The only way to solve your use case is to add at the end of your block code an /

```
BEGIN
SELECT mycol from myTable;
END;
/
```
I have adopted the syntax from oracle SQL+ tool.
